export default APPSETTINGS = {
    app_name:"Market",
    colors:{
        default:{
            app_primary:"whitesmoke",
            app_secondary:"white",
            app_danger:"#ff0040",
            app_statusBar_backgroundColor:"#27ae60",
            app_textColor_primary:"#00000099",
            app_textColor_secondary:"green",
            app_textColor_link:"green",
            app_image_tinColor:"#27ae60",
            app_header_backgroundColor:"white",
            app_box_backgroundColor:"white",
            app_loading:"whitesmoke",
            app_bottomTabs_backgroundColor:"white",
            app_button_backgroundColor:"#27ae60",
            app_textInput_borderColor:"#27ae60",
        },
        dark:{
            app_primary:"#07070f",
            app_secondary:"#142424",
            app_danger:"#ff000d",
            app_statusBar_backgroundColor:"#1a1a24",
            app_textColor_primary:"whitesmoke",
            app_textColor_secondary:"white",
            app_textColor_link:"green",
            app_image_tinColor:"white",
            app_header_backgroundColor:"#1a1a24",
            app_box_backgroundColor:"#1a1a24",
            app_loading:"transparent",
            app_bottomTabs_backgroundColor:"#1a1a24",
            app_button_backgroundColor:"#27ae60",
            app_textInput_borderColor:"white",
        }
    },
    font_size:{
        default:{
            app_large_FontSize:20,
            app_medium_FontSize:16,
            app_small_FontSize:12,
        },
        small:{
            app_large_FontSize:18,
            app_medium_FontSize:14,
            app_small_FontSize:10,
        },
        medium:{
            app_large_FontSize:20,
            app_medium_FontSize:16,
            app_small_FontSize:12,
        },
        large:{
            app_large_FontSize:22,
            app_medium_FontSize:18,
            app_small_FontSize:14,
        }
    }
}