//trial data
const DUMMYDATA = [{category:"clothing",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:1,
    product_name:"Trouser",
    product_price:"1,100",
    product_image:"",
    product_rating:3.7,
    product_description:"nice cloth."},
    {pid:2,
    product_name:"T-shirt",
    product_price:"1,100",
    product_image:"",
    product_rating:3.7,
    product_description:"nice t-shirt."}]},
{category:"food stuff",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:3,
    product_name:"Cooking oil",
    product_price:"900",
    product_image:"",
    product_rating:4.7,
    product_description:"nice cooking oil."}]},
{category:"Phones",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:4,
    product_name:"Gionee",
    product_price:"6,100",
    product_image:"",
    product_rating:3.9,
    product_description:"nice phone."},{pid:5,
        product_name:"Iphone X",
        product_price:"61,000",
        product_image:"",
        product_rating:3.9,
        product_description:"nice Knife."},]},
{category:"Utensils",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:5,
        product_name:"Knife",
        product_price:"6,100",
        product_image:"",
        product_rating:3.9,
        product_description:"nice Knife."}]},
{category:"Electronics",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:6,
        product_name:"Computer CPU",
        product_price:"9,900",
        product_image:"",
        product_rating:3.9,
        product_description:"nice cloth."},
    ]},
{category:"New",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:7,
        product_name:"Tesla charger",
        product_price:"24,000",
        product_image:"",
        product_rating:3.9,
        product_description:"nice charger."}]},
{category:"New products",brands:["brand 1","brand 2","brand 3","brand 4"],items:[{pid:8,
        product_name:"New product",
        product_price:"14,700",
        product_image:"",
        product_rating:3.9,
        product_description:"nice product."}]}
        ];

    export default DUMMYDATA;